# speed param
control:
  speed:
    x: 0.0
    y: 0.0
    z: 0.0
  angle:
    x: 0.0
    y: 0.0
    z: 0.0
  # default param
line:
  point:
    x: 0.0
    y: 0.0
    z: 0.0
  angle:
    z: 0.0
  flag: false
land:
  point:
    x: 0.0
    y: 0.0
    z: 0.0
  angle:
    z: 0.0
  flag: false
door:
  point:
    x: 0.0
    y: 0.0
    z: 0.0
  angle:
    z: 0.0
  flag: false
QR:
  info:
    high: 0
    order: 1
    direction: 0
  flag: false