params:
  speed:
    x: 0.0
    y: 0.0
    z: 0.0
  other:
    threadrosout: false
state:
  pose:
    x: 0.0
    y: 0.0
    z: 0.0
  angle:
    x: 0.0
    y: 0.0
    z: 0.0
  speed:
    normal: 0.3
    high: 0.45
    low: 0.6
  mode:
    current: land
point:
  pose:
    x: 0.0
    y: 0.0
    z: 0.7