# 0.85 测试最好
autopid:
  pose_z:
    kp: 0.65
    ki: 0
    kd: 0.45
    kcoef: 1.2
    lasterror: 0.0
    sumerror: 0.0
    vMax: 1.2
    vMin: -1.2
    dcoef: 0.0005
    wp: 0.1
    wi: 0.0
    wd: 0.1
  pose_x:
    kp: 0.55
    ki: 0.0
    kd: 0.25
    kcoef: 0.8
    lasterror: 0.0
    sumerror: 0.0
    vMax: 0.4
    vMin: -0.4
    dcoef: 0.0005
    wp: 0.1
    wi: 0.0
    wd: 0.1
  pose_y:
    kp: 0.5
    ki: 0.03
    kd: 0.05
    kcoef: 1.3
    lasterror: 0.0
    sumerror: 0.0
    vMax: 0.4
    vMin: -0.4
    dcoef: 0.0005
    wp: 0.1
    wi: 0.1
    wd: 0.1
normalpid:
  pose_x:
    lasterror: 0.0
    sumerror: 0.0
    kp: 0.4
    ki: 0.0
    kd: 0.05
  pose_y:
    lasterror: 0.0
    sumerror: 0.0
    kp: 0.4
    ki: 0.0
    kd: 0.05
  pose_z:
    lasterror: 0.0
    sumerror: 0.0
    kp: 1.2
    ki: 0.0
    kd: 0.2
  angle_z:
    lasterror: 0.0
    sumerror: 0.0
    kp: 0.075
    ki: 0.0
    kd: 0.01