# 0.85 测试最好
autopid:
  pose_z:
    kp: 0.65
    ki: 0
    kd: 0.45
    kcoef: 1.2
    lasterror: 0.0
    sumerror: 0.0
    vMax: 1.2
    vMin: -1.2
    dcoef: 0.0005
    wp: 0.1
    wi: 0.0
    wd: 0.1
  pose_x:
    kp: 0.55
    ki: 0.0
    kd: 0.25
    kcoef: 0.8
    lasterror: 0.0
    sumerror: 0.0
    vMax: 0.4
    vMin: -0.4
    dcoef: 0.0005
    wp: 0.1
    wi: 0.0
    wd: 0.1
  pose_y:
    kp: 0.3
    ki: 0.0
    kd: 0.25
    kcoef: 0.45
    lasterror: 0.0
    sumerror: 0.0
    vMax: 0.4
    vMin: -0.4
    dcoef: 0.0005
    wp: 0.1
    wi: 0.0
    wd: 0.1
normalpid:
  pose_x:
    vMax: 0.5
    vMin: -0.5
    lasterror: 0.0
    sumerror: 0.0
    kp: 0.7
    ki: 0.0
    kd: 0.2
  pose_y:
    vMax: 50
    vMin: -50
    lasterror: 0.0
    sumerror: 0.0
    kp: 0.3
    ki: 0.0
    kd: 0.05
  pose_z:
    vMax: 1.2
    vMin: -1.2
    lasterror: 0.0
    sumerror: 0.0
    kp: 1.45
    ki: 0.35
    kd: 0.35
  angle_z:
    vMax: 0.4
    vMin: -0.4
    lasterror: 0.0
    sumerror: 0.0
    kp: 0.075
    ki: 0.0
    kd: 0.01